-- warehouse permissions
GRANT USAGE, OPERATE ON WAREHOUSE DEV_WH TO ROLE CICD_ALL_ROLE;

-- database & schema permissions
GRANT CREATE DATABASE ON ACCOUNT TO ROLE CICD_ALL_ROLE;

-- grants, user & role permissions
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE CICD_ALL_ROLE;
GRANT CREATE USER ON ACCOUNT TO ROLE CICD_ALL_ROLE;
GRANT CREATE ROLE ON ACCOUNT TO ROLE CICD_ALL_ROLE;
