USE DATABASE OPERATIONS;
USE SCHEMA TERRAFORM;

CREATE TABLE IF NOT EXISTS CHANGE_HISTORY (
    VERSION VARCHAR
    , DESCRIPTION VARCHAR
    , SCRIPT VARCHAR
    , SCRIPT_TYPE VARCHAR
    , CHECKSUM VARCHAR
    , EXECUTION_TIME NUMBER
    , STATUS VARCHAR
    , INSTALLED_BY VARCHAR
    , INSTALLED_ON TIMESTAMP_LTZ
);
